name: Enforce code style

on:
  pull_request:
    paths:
      - '**.php'
      - 'pint.json'
  push:
    paths:
      - '**.php'
      - 'pint.json'
  workflow_dispatch:

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style
          commit_user_name: laravel-pint
