name: Enforce code style

on:
  pull_request:
    paths:
      - '**.php'
  push:
    paths:
      - '**.php'
  workflow_dispatch:

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style
